### ISSUE TITLE
make sure all of our images use a decent processmanager

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#1]
make sure all of our images use a decent processmanager like supervisord or zinit

**Comment by hossnys** [comment]
i just checked , crm , faveo , taiga , Humhub , odoo and they are done using supervisord ,
the remaining are discourse , gitea , wordpress , to be checked with the team , @Pishoy  and @PeterNashaat  please update with the status of this images.

**Comment by Pishoy** [comment]
- working in discourse to convert it using supervisord

**Comment by Pishoy** [comment]
- discourse supervisor is ready but have issue with unicron starting @PeterNashaat is checking it
- freeflowpages flist has been added by supervisord 
- working in converting a circles flist to supervisord

**Comment by Pishoy** [comment]
circles flist done and tested in docker and ZerOS container and docs in https://github.com/threefoldtech/tf-images/tree/master/circles

**Comment by Pishoy** [comment]
@Hamdy please check issue https://github.com/Incubaid/crm/issues/159

**Comment by Pishoy** [comment]
as per Hamdy, no integration for  crm now , will check later

as there is issue for that in crm repo, an all images done,closing this
