### ISSUE TITLE
Kubernetes - K3S_TOKEN is not used in deployment

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tf-images#100]
The Kubernetes image does not actually use the `K3S_TOKEN` passed in as an environment variable.

**Comment by AhmedHanafy725** [comment]
it uses the token to let the worker join the master, and it can be mentioned in the command with `--token` or exported as environment variable `K3S_TOKEN`
https://docs.k3s.io/reference/server-config#cluster-options

**Comment by scottyeager** [comment]
Ah, I see now, the token is taken implicitly by `k3s` from the environment variable. I tried killing and restarting the `k3s` server to change some options, and it didn't recognize the token when starting up again. The issue is that the environment variable doesn't get applied to the new session when connecting via ssh.

Thanks for the explanation.
