### ISSUE TITLE
discourse image is using wrong base

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#11]
it depends on `threefolddev/tf_discourse:latest`, how was that built? 

Make sure the Dockerfile has all of the information needed and the right base image.

**Comment by Pishoy** [comment]
`threefolddev/tf_discourse:latest ` is a manual flist whout dockerfile, gonna check how to automate that as dockerfile

**Comment by Pishoy** [comment]
manuall flist has been removed and all automated on dockerfile 
https://github.com/threefoldtech/tf-images/blob/master/discourse_3bot/Dockerfile
