### ISSUE TITLE
update mastodon image

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#110]
should include codeserver, webmin, iproute2, htop, rsync, net-tools, mc, mcedit, caddy

**Comment by xmonader** [comment]
@AhmedHanafy725 will help with the caddy configurations

**Comment by Omarabdul3ziz** [comment]
updates:
- finish installing of the packages. 
- codeserver and webmin up and running.
- still wip on caddy configurations (some blocks hope get it done tmw isA)

**Comment by Mahmoud-Emad** [comment]
Should include a script to add all available relays, and create new Unix user to some requirements in Webmin

**Comment by A-Harby** [comment]
Verified.
![image](https://user-images.githubusercontent.com/109473873/216016867-58b49c8e-0a0d-4cbd-ba54-408c17c6babb.png)

codeserver
![image](https://user-images.githubusercontent.com/109473873/216016927-08bc1f7a-8647-487f-ad53-2da5e5ba5cd5.png)
webmin
![image](https://user-images.githubusercontent.com/109473873/216016980-50e7d0dd-4f59-4385-b899-8965df5a2278.png)
