### ISSUE TITLE
Update mastodon image, Support tf-connect 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tf-images#112]
### Related Issues
[#1118- support tf-connect enabled version of mastodon](https://github.com/threefoldtech/grid_weblets/issues/1118)

**Comment by mohamedamer453** [comment]
Verified from https://getmastodon.threefold.io/

The image now supports logging in with threefold connect.

[Untitled_ Nov 29, 2022 5_39 PM.webm](https://user-images.githubusercontent.com/101194226/204574596-defe15aa-0a92-49d4-b7dc-1ebd067a7a4b.webm)
