### ISSUE TITLE
create Umbrel image

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tf-images#126]

**Comment by 0oM4R** [comment]
Umbrel creates < using docker-compose > 5 containers for different functions, 
I tried to build a single docker image with those containers as services managed by zinit,
but I didn't find to source dockerfile of one of them ` image: getumbrel/tor:0.4.7.8`. 
For now, I think there is no way to run Umbrel without docker-compose!
so I'm trying to build an image like [subsquid](https://github.com/threefoldtech/tf-images/tree/development/tfgrid3/subsquid)

**Comment by 0oM4R** [comment]
image works fine sometimes, but many times I got this error 
````
Unable to find image 'getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
See 'docker run --help'.
```

**Comment by 0oM4R** [comment]
almost done just need to test it on the grid and with the gw

**Comment by 0oM4R** [comment]
faced some issues while applying ufw, and the installed app on Umbrel, resolved now and I will continue enhancing it tmw isA

**Comment by A-Harby** [comment]
Verified, Image is working fine
![image](https://user-images.githubusercontent.com/109473873/227220694-ac97f64d-d278-413f-ba4b-59053de02d2d.png)
