### ISSUE TITLE
K3s: multiple errors are returned while executing `kubectl get nodes` in the grid3_client_ts integration tests

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tf-images#133]
### Description 

Original Issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/15

New K3s images returns multiple errors when i execute `kubectl get nodes` during grid3_client_ts integration tests.

the mentioned errors are

```
    `E0403 11:25:41.861009    2839 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused\n` +
      `E0403 11:25:41.862936    2839 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused\n` +
      `E0403 11:25:41.864878    2839 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused\n` +
      `E0403 11:25:41.866937    2839 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused\n` +
      `E0403 11:25:41.868028    2839 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused\n` +
      'The connection to the server localhost:8080 was refused - did you specify the right host or port?'
```

More info can be found in the original issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/15

to confirm that the issue is related to  the new image, i tried to run the same test with the old image and it passed and returned the master/worker status without any issues. https://github.com/threefoldtech/tfgrid-sdk-ts/issues/15 

and for further confirmation i removed the 20 second timeout built in the tests to ensure that the cluster started successfully and indeed when i executed `kubectl get nodes` then it didn't return the master/worker status but it also didn't return the errors mentioned above but it returned `stderr: 'No resources found'`

![image](https://user-images.githubusercontent.com/101194226/229530337-166d70d8-5190-4bd1-9252-7e3fa67e8e36.png)

The old flist that i mentioned above is `https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-k3s-v1.22-latest.flist`

**Comment by sameh-farouk** [comment]
**Update:**
No changes required from the image side. please see my comment here: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/15#issuecomment-1562687744
