### ISSUE TITLE
k8s: base image need to make sure `ntpd` is running 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tf-images#134]
ntpd is needed to make sure VM clock is always in sync with a time server! If it's not running a clock skew can accumulate over time causing may ssl services to stop working!

if the ntpd binary is not part of the image please make sure it's installed (although it's probably is) then make sure this config file in zinit is included

/etc/zinit/ntpd.yaml 

```yaml
exec: ntpd -n
```

**Comment by AhmedHanafy725** [comment]
it's running on the new flist just built and deployed on devnet.

![image](https://user-images.githubusercontent.com/41957921/231146162-e9686f6a-b0eb-4a63-98c9-7cc5a7032b9a.png)

**Comment by AhmedHanafy725** [comment]
@maxux please promote this flist
https://hub.grid.tf/hanafy.3bot/threefolddev-k3s-latest.flist -> https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist

**Comment by maxux** [comment]
Promoted :)
