### ISSUE TITLE
Taiga image takes alot of time/resources to build

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tf-images#14]
- In the entrypoint we have a list of python requirements and apt packages
- git cloning for more than one repo
- building frontend and Django migrations
- should be tested against zos container

that all should be in the image to save time, also it may lead to failures on zos containers

image: https://github.com/threefoldtech/tf-images/tree/master/taiga_all_in_one

**Comment by xmonader** [comment]
because these operations should be done in the image layers NOT after the container starts

**Comment by waleedhammam** [comment]
refactored at: https://github.com/threefoldtech/tf-images/tree/master/taiga_io
