### ISSUE TITLE
Promote Debian List to tf-official-apps

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tf-images#155]
@maxux 

Could you promote the following? I don't have access to promote from tf-official-apps.

> https://hub.grid.tf/ahmedthabet.3bot/threefolddev-debian-12.flist

to

> https://hub.grid.tf/tf-official-apps/threefoldtech-debian-12.flist

I think the command would be:

```
curl -b "active-user=tf-official-apps;" -H "Authorization: bearer ...token..." \
    "https://hub.grid.tf/api/flist/me/promote/ahmedthabet.3bot/threefolddev-debian-12.flist/threefoldtech-debian-12.flist"
```

Then we can publish the Debian FList in this [PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/913) on tfgrid-sdk-ts.

(Proposed my Thabet [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/913#issuecomment-1670151107))

Thank you!

**Comment by maxux** [comment]
https://hub.grid.tf/tf-official-apps/threefoldtech-debian-12.flist.md
