### ISSUE TITLE
Promote Nextcloud AIO

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tf-images#157]
Hi again @maxux !

Could you promote the following?

> https://hub.grid.tf/idrnd.3bot/logismosis-nextcloudaio-latest.flist

to

> https://hub.grid.tf/tf-official-apps/threefoldtech-nextcloudaio-latest.flist

Then we can publish the official Nextcloud FList in this [PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/960)

Feel free to do the flist yourself or to check the Dockerfile et al. [here.](https://github.com/threefoldtech/tf-images/tree/development_nextcloudaio/tfgrid3/nextcloud)

The mentioned PR is being revised by @AhmedHanafy725 and @MohamedElmdary

**Comment by maxux** [comment]
Hello :)

```
idrnd.3bot/logismosis-nextcloudaio-latest.flist -> tf-official-apps/threefoldtech-nextcloudaio-latest.flist
```
https://hub.grid.tf/tf-official-apps/threefoldtech-nextcloudaio-latest.flist.md

**Comment by mik-tf** [comment]
Thanks so much @maxux 

Have a good day :)

**Comment by scottyeager** [comment]
Hey @maxux,

We'd like to replace this one as folows:

```
https://hub.grid.tf/scott.3bot/scottyeager-nextcloud_disk-caddy-v2.flist -> tf-official-apps/threefoldtech-nextcloudaio-latest.flist
```

Thanks :)

**Comment by maxux** [comment]
Updated :)

**Comment by scottyeager** [comment]
Thanks!

**Comment by scottyeager** [comment]
Hi @maxux,

Need to update this one again:

```
https://hub.grid.tf/scott.3bot/scottyeager-nextcloud_disk-caddy-v4.flist -> tf-official-apps/threefoldtech-nextcloudaio-latest.flist
```

Thanks!

**Comment by maxux** [comment]
Promoted :)

**Comment by scottyeager** [comment]
Hi @maxux,

We need a new Nextcloud image promoted:

```
https://hub.grid.tf/scott.3bot/scottyeager-nextcloud-grid-latest.flist -> tf-official-apps/threefoldtech-nextcloudaio-latest.flist
```

Thanks.

**Comment by maxux** [comment]
Promoted :)
