### ISSUE TITLE
WordPress uploads folder owned by root

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tf-images#163]
When the WordPress image is deployed, the folder `/var/www/html/wp-content/uploads/` is owned by `root` and thus the user can't upload any media without changing the owner to `www-data`.

I think this happens because the WordPress installer is being run as root [here](https://github.com/threefoldtech/tf-images/blob/860273f490221cab027030a4f586d44b93555837/tfgrid3/wordpress/scripts/wp_entrypoint.sh#L116). I'm not sure if running it as the `www-data` user is a better idea, or if there are any other undesired side effects from running as root.

Executing this resolves the issue, and could be included in the script:

`chown -R www-data:www-data /var/www/html/wp-content/uploads/`

**Comment by AhmedHanafy725** [comment]
@maxux can you please promote this flist?
https://hub.grid.tf/hanafy.3bot/threefolddev-wordpress-latest.flist -> https://hub.grid.tf/tf-official-apps/tf-wordpress-latest.flist

**Comment by maxux** [comment]
Updated :)

**Comment by A-Harby** [comment]
Verified, Devnet f86490f.
File ownership changed to `www-data` using https://hub.grid.tf/tf-official-apps/tf-wordpress-latest.flist.
![image](https://github.com/threefoldtech/tf-images/assets/109473873/8c78119d-7147-455f-bdfa-961acea9dd7a)

@scottyeager Can you tell the command or steps used to upload media, to create a test case for it.

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tf-images/assets/109473873/8f56d6df-2f18-4ef5-bee2-c1f50f565ab9)

Test steps:
https://app.testlodge.com/a/26076/projects/40893/suites/227225?expand_section=397795#case_4077464
