### ISSUE TITLE
SSH host keys are baked into the flists

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tf-images#165]
When `openssh-server` is installed into an Ubuntu container, it generates host keys and places them under `/etc/ssh`. Since there's no logic in our images to regenerate these keys after deployment, the result is that every VM deployed from the same image has the same host keys by default.

One approach to remedy this would be to remove them inside the Docker file, and then add a step to the ssh-init script that generates the keys if they don't exist. The downside to this is that if the removal step is omitted from the Dockerfile, when an image is copied as an example for instance, then the old behavior returns.

Another approach would be to replace any keys that exist on disk on the first boot. This would also require adding an artifact on the filesystem somewhere to signal that the step has been completed, since zinit oneshots run on every boot.

Either way, the two steps can be achieved like this:

```
rm /etc/ssh/ssh_host_*
ssh-keygen -A
```

**Comment by scottyeager** [comment]
After some further thought, I am wondering if this is better handled by [cloud-container](https://github.com/threefoldtech/cloud-container/), as part of its `cloud-init` implementation. The mainline implementation [itself has](https://github.com/canonical/cloud-init/blob/9a401b4a21ea179452143ef8c97f261c1655c539/cloudinit/config/cc_ssh.py#L80) features for handling this exact scenario, by deleting host keys shipped with an image and replacing them at time of first boot.

This has several advantages:

1. No need to enforce the behavior within images as updates are made to this repo (with [#139](https://github.com/threefoldtech/tf-images/issues/139) also implemented, images don't need to be concerned with ssh keys whatsoever)
2. No need to regenerate all of the existing flists that have the hard coded keys
3. If we later want to also support the `cloud-init`  feature where the user passes in pregenerated host keys, we don't need to regenerate all the flists to do that either

What do you think @muhamadazmy?

**Comment by muhamadazmy** [comment]
IMHO it's not good idea to handle this in cloud-container otherwise we will be deleting this file  blindly. What if the author of the flist is indeed want to use that specific host key? cloud-container is just our own very tiny implementation of cloud-init with a pre-built kernel to be able to run flists that don't have their own kernel according to specs, and we still need to apply network settings. 

So i really think the right place to do the clean up is during the build (in this repo) of the flist, have the proper scripts to clean regenerate the keys when they don't exist.

If you using a full fledged linux disto, (includes the kernel like [here](https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/zmachine.md#vm))  it's encouraged to use cloud-init which will take care of this on boot.

The system (zos and all its utilities) should not assume a certain flist structure or software.

**Comment by scottyeager** [comment]
Shipping host keys inside an flist is never a wise approach within our current architecture, because all flists are on public links. If we plan to support authenticated repositories for flists in the future, then it's a potential use case but a niche one.

Users who want to supply host keys into their micro VMs should do so through environment variables and scripts. That's the correct approach today and is probably still the correct approach if private flists are later supported (keep the software and the secrets separate).

On the other hand, the majority of users who just want a unique and securely generated set of host keys don't get a sane default behavior in the current system. All of the images in this repo, from a variety of contributors, have the same issue. I can practically guarantee that no matter how well we document it, users creating their own flists will also end up with hard coded host keys.

> The system (zos and all its utilities) should not assume a certain flist structure or software.

Currently, `cloud-container`  handles injecting the ssh authorized key, so it's already assumed that an ssh server might be present. I think that's the correct approach and that also providing basic host key handling is a logical complement.

With `clout-init`, the default behavior is to delete any host keys present in the VM image and generate fresh ones. Users can optionally set `ssh_deletekeys` to false to retain them. That means we actually don't currently support retaining host keys in full VMs or installing user supplied host keys, since we don't support custom `cloud-init` config.

So I'm just suggesting that we extend the very sensible example set by `cloud-init` into our implementation for micro VMs and thus also create a consistent behavior across the VM types.

**Comment by scottyeager** [comment]
Closing this, as host key cleanup will be done in Zos, and host key generation will be done in cloud-container (https://github.com/threefoldtech/cloud-container/issues/18).
