### ISSUE TITLE
please merge all branches

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tf-images#174]
<img width="455" alt="image" src="https://github.com/threefoldtech/tf-images/assets/6021844/11559528-f686-4181-b3fd-9224698c9e95">

**Comment by sameh-farouk** [comment]
Update:
Most of them merged or cleaned already.
Only few remains, will merge when works on these branches is done.

@scottyeager please check if you need this branch here https://github.com/threefoldtech/tf-images/tree/development_nextcloud_gateway ? i think it is a duplicate.

**Comment by scottyeager** [comment]
> @scottyeager please check if you need this branch here https://github.com/threefoldtech/tf-images/tree/development_nextcloud_gateway ? i think it is a duplicate.

Indeed, this one is no longer needed since I squashed the contents to the other branch. I've deleted it.
