### ISSUE TITLE
disabling dependsbot requires admin access

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tf-images#175]
`tfgrid3/forum` is a deprecated image that is not used anymore. we have been using `tfgrid/forum-3` 
dependabot keeps spamming by opening prs to update modules in `requirements.txt` for example: https://github.com/threefoldtech/tf-images/pull/144 and we keeps closing the pr.

can we disable dependabot? it requires admin access to settings.

**Comment by hossnys** [comment]
- closed these two new PR opened by dependabot , and disabled that dependabot feature of creating PRs automatically . 
![Screenshot from 2024-05-09 11-54-32](https://github.com/threefoldtech/tf-images/assets/26298009/25b14362-c372-425e-9497-a5e12363fcde)
