### ISSUE TITLE
create a docker image of the latest working version of the library

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#184]
https://library.threefold.me/info/threefold#/tokens/threefold__stats_token_overview

check the commit that works and build an image for it

**Comment by ashraffouda** [comment]
created a tag and a release for the working version of crystallib that works so we don't loose that commit again 
also hardcoded the vlang version on the docker file to a the weekly release that worked with this code in both crystallib and crystal tools
https://github.com/freeflowuniverse/crystaltools/pull/132/files
https://github.com/threefoldtech/tf-images/pull/186
