### ISSUE TITLE
More application images

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tf-images#195]
# Request

related to [this ourworld.tf issue](https://git.ourworld.tf/threefold_coop/circle_prodmgmt_grid/issues/3)

# new images 

- [ ] #196
- [x] #197
- [x] #199
- [x] #201
- [x] #202

**Comment by xmonader** [comment]
@sabrinasadik new images been required

**Comment by PeterNashaat** [comment]
https://github.com/threefoldtech/tf-images/issues/199, https://github.com/threefoldtech/tf-images/issues/200 and https://github.com/threefoldtech/tf-images/issues/201  these 3 issues need a way how to see Mycelium addr in UI (Portal) and i don't know how to do that exactly. the rest of the images are done.

**Comment by xmonader** [comment]
the integration in the UI will be done by development, but you can already continue on the rest indeed :)

**Comment by PeterNashaat** [comment]
- https://github.com/threefoldtech/tf-images/issues/199 and https://github.com/threefoldtech/tf-images/issues/201 are done.

**Comment by zaelgohary** [comment]
> * [VM: Ubuntu 23.10 with Mycelium #199](https://github.com/threefoldtech/tf-images/issues/199) and [VM: Arch, with Mycelium #201](https://github.com/threefoldtech/tf-images/issues/201) are done.

@PeterNashaat Can we have the official flists for both Arch & Ubuntu 23.10?

**Comment by PeterNashaat** [comment]
on it

**Comment by xmonader** [comment]
can this be closed?	@PeterNashaat

**Comment by PeterNashaat** [comment]
yes can be closed, images were promoted to official flists tf-official-vms/ubuntu-23.10-mycelium.flist, tf-official-vms/arch-mycelium.flist
i was waiting for gitea image to be verified https://github.com/threefoldtech/tf-images/issues/202#issuecomment-2188120279 but i verified it myself and it's working as expected.
please reopen if anything else needed
