### ISSUE TITLE
NOSTR Node (mycelium, optional pub ip)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#197]

**Comment by PeterNashaat** [comment]
- Created raw image with nostr relau node and mycelium
```7.3G    image.raw```
- Compressed it to tar.gz file to be uploaded to the hub
```2.8G    nostr_relay-mycelium.tar.gz```

- Created a dockerfile for nostr_relay + mycelium
https://github.com/threefoldtech/tf-images/commit/ab8753722cef72961eb22bc24bbacb8334284f9d

**Comment by PeterNashaat** [comment]
- Created nostr relay with mycelium Dockerfile https://github.com/threefoldtech/tf-images/tree/btc-node-mycelium/tfgrid3/nostr_relay-mycelium
- Created Flist https://hub.grid.tf/petep.3bot/nostr_relay-mycelium.flist.md
- Tested
<img width="573" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/72649309-199c-480f-abc0-421005bb3bb0">

<img width="1407" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/2295bb55-bb6d-4cc7-8114-96b35a45f8b3">

**Comment by PeterNashaat** [comment]
- Reopen if anything else is needed.
