### ISSUE TITLE
VM: Ubuntu 23.10 with Mycelium

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#199]

**Comment by PeterNashaat** [comment]
- Flist created https://hub.grid.tf/petep.3bot/ubuntu23.10_mycelium.flist.md
- https://github.com/threefoldtech/tf-images/commit/f6e1806471d4aa30fa8986a1235d62c894f6eea8
- Tested :
![image](https://github.com/threefoldtech/tf-images/assets/13523434/d513d935-b3e1-42a4-adf9-1238c520b0c5)
![image](https://github.com/threefoldtech/tf-images/assets/13523434/d3c81d6c-1c2b-40e7-ad2f-537b4586687b)
