### ISSUE TITLE
Add info to peertube

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tf-images#2]
- Add flist link 
 - Can you add documentation on how to run it, env variable, which endpoint should i use while creating container on zos v2 grid

**Comment by OmarElawady** [comment]
I added the dockerfile info [here](https://github.com/threefoldtech/tf-images/tree/peertube/peertube)

**Comment by PeterNashaat** [comment]
- {domain_name} {email} are these env variable as well ?

**Comment by OmarElawady** [comment]
No, they are actual arguments that get passed to the startup script. They are entered in the chatflow.

**Comment by hossnys** [comment]
verified 
- docs [here](https://github.com/threefoldtech/tf-images/blob/master/peertube/README.md)
- only required info are solution name , email , storage size, poo;l ,network .

![Screenshot from 2020-08-24 21-17-56](https://user-images.githubusercontent.com/26298009/91086907-db0ba600-e64f-11ea-8681-7ce31f05af95.png)

![Screenshot from 2020-08-24 21-17-40](https://user-images.githubusercontent.com/26298009/91086903-d9da7900-e64f-11ea-8dca-ad6d4e3b7c57.png)
