### ISSUE TITLE
VM: Arch, with Mycelium

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#201]

**Comment by PeterNashaat** [comment]
- Flist created [link](https://hub.grid.tf/petep.3bot/arch_mycelium.flist.md)
- Pushed [code](https://github.com/threefoldtech/tf-images/commit/5e82d742cc2a0b5adc4264280a85172fa746a02b)
- Tested
<img width="1059" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/c75bbfe0-26c3-42d7-b03c-a3822389493c">

<img width="707" alt="image" src="https://github.com/threefoldtech/tf-images/assets/13523434/bcd0bc1e-26a5-4972-8141-eb8581257ab1">
