### ISSUE TITLE
Update Taiga image

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tf-images#230]
Taiga instances give ```Bad Gateway```

**Comment by hossnys** [comment]
- issue fixed here https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2727 , so @zaelgohary please arrange who is gonna verify it , then close this one .

**Comment by zaelgohary** [comment]
Verified [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2727#issuecomment-2119265077)
