### ISSUE TITLE
update k3s to latest

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#240]

**Comment by hossnys** [comment]
changes are [here](https://github.com/threefoldtech/tf-images/commit/5e38e69c7e12b6df94767f0988465d06bca99160) , and flist created : https://hub.grid.tf/samir1.3bot/threefolddev-k3s-latest.flist
, once the image tested , will create a PR for it .

**Comment by hossnys** [comment]
ended up with this error found when visited consol_url of that vm :
![Screenshot from 2024-05-09 20-08-34](https://github.com/threefoldtech/tf-images/assets/26298009/ac09c970-15cb-468c-a6f6-7dd74bc97221)

will continue investigation with the team on Sunday

**Comment by hossnys** [comment]
- fixed ssh [here](https://github.com/threefoldtech/tf-images/commit/f2081c3077914cea83fbf4882647f5b7f4c5182b#diff-9a233adc5597c06f4e68a9a1b6a4ccec05fcc54137e3e20cb4c74c03bf6fbec2)
- will build image and test deployment on dashboard

**Comment by hossnys** [comment]
- found that k3s released new version v1.30.0+k3s1 so I added it [here](https://github.com/threefoldtech/tf-images/commit/fb1a0c83e68e41057cac2440def0cef0ebd5dfd5) , and created the image again .
- but after testing the image , we got this error in zinit log which is reported [here](https://github.com/threefoldtech/zos/issues/2327)
```
[+] k3s: time="2024-05-12T14:30:59Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: \"overlayfs\" snapshotter cannot be enabled for \"/var/lib/rancher/k3s/agent/containerd\", try using \"fuse-overlayfs\" or \"native\": failed to mount overlay: invalid argument"
```

**Comment by hossnys** [comment]
- for now after fixing traefik [here](https://github.com/threefoldtech/tf-images/commit/d24a824a10baf3a6b132707c2caa386eb8f2e72e) and building image again , it's tested and working fine :

![01](https://github.com/threefoldtech/tf-images/assets/26298009/811bdcf2-af6f-4da9-a7a5-769409f359d9)

![Screenshot from 2024-05-12 17-42-07](https://github.com/threefoldtech/tf-images/assets/26298009/6dfa0855-cb7f-4a2b-825c-32097f37226c)

- now we can to promote it @maxux please promote 
https://hub.grid.tf/samir1.3bot/threefolddev-k3s-latest.flist to be https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist

- here is the PR for it : #249

**Comment by maxux** [comment]
Promoted :)

**Comment by hossnys** [comment]
flist promoted , will close this issue once PR merged

**Comment by hossnys** [comment]
done
