### ISSUE TITLE
Alpine 3

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tf-images#245]

**Comment by PeterNashaat** [comment]
- [Flist](https://hub.grid.tf/petep.3bot/alpine3.flist.md) creatad and tested
![image](https://github.com/threefoldtech/tf-images/assets/13523434/14ae9f2c-c568-427e-b2db-d80784061ad2)
- Pull request https://github.com/threefoldtech/tf-images/pull/248

**Comment by khaledyoussef24** [comment]
tried multiple deployments but did not work with multiple ssh
<img width="568" alt="Screenshot 2024-05-20 at 12 23 34 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/373d0be6-c583-4092-a89d-caf8cb9930c9">
<img width="659" alt="Screenshot 2024-05-20 at 12 23 39 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2e687a12-0ad6-4376-a034-58440307e943">
![Screenshot 2024-05-20 at 12 23 47 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/414a1a26-79f3-4abc-a991-6d7d17a939a0)
