### ISSUE TITLE
CentOS 8

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tf-images#246]

**Comment by PeterNashaat** [comment]
- As CentOS 8 reached EOL, updated it to CentOS Stream 9
- [Flist](https://hub.grid.tf/petep.3bot/centos-stream9.flist.md) creatad and tested
![image](https://github.com/threefoldtech/tf-images/assets/13523434/4d6d2264-b894-402b-bce7-57fcf35a6555)
- Pull request https://github.com/threefoldtech/tf-images/pull/248

**Comment by khaledyoussef24** [comment]
tried multipe deployments but did not work with multiple ssh
<img width="573" alt="Screenshot 2024-05-20 at 12 05 21 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b69fddaa-097f-4079-b509-e5efa341d6dc">
<img width="622" alt="Screenshot 2024-05-20 at 12 05 39 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ef606e11-d97a-4cc1-b05c-e32746ccc3a1">
![Screenshot 2024-05-20 at 12 14 58 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9a321784-892d-4a8f-876c-63210cf6bedd)
