### ISSUE TITLE
Promote Static Website Flist to an official one

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tf-images#259]
@maxux 

Can you please promote the following flist to an official one?
[https://hub.grid.tf/mayarosamaa.3bot/mayarosama-staticwebsite-latest.flist](https://hub.grid.tf/mayarosamaa.3bot/mayarosama-staticwebsite-latest.flist)

**Comment by maxux** [comment]
Here you are: https://hub.grid.tf/tf-official-apps/mayarosama-staticwebsite-latest.flist.md

I can rename it if you want :)

**Comment by maayarosama** [comment]
> Here you are: https://hub.grid.tf/tf-official-apps/mayarosama-staticwebsite-latest.flist.md
> 
> I can rename it if you want :)

can we remove mayarosama from the name please?

**Comment by maxux** [comment]
Updated :)

**Comment by PeterNashaat** [comment]
- flist promoted and name was updated https://hub.grid.tf/tf-official-apps/staticwebsite-latest.flist, can be close now.
