### ISSUE TITLE
Peertube

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tf-images#268]
https://github.com/threefoldtech/tf-images/tree/development/tfgrid3/peertube

**Comment by PeterNashaat** [comment]
- Created new flist that support multiple ssh  https://hub.grid.tf/petep.3bot/peertube.flist.md .
- Created pull request with new changes https://github.com/threefoldtech/tf-images/pull/269
![image](https://github.com/threefoldtech/tf-images/assets/13523434/d2e13f3e-03c3-49ef-81de-3c9def515e40)

![image](https://github.com/threefoldtech/tf-images/assets/13523434/49b46c47-7263-4c9f-a9f9-5058085794c2)
![image](https://github.com/threefoldtech/tf-images/assets/13523434/8aad4792-941c-4959-84d5-e10424c75451)

**Comment by Omdaany** [comment]
Can we promote this flist?

**Comment by ghost** [comment]
@maxux 
Can we promote this [flist](https://hub.grid.tf/petep.3bot/peertube.flist)?

**Comment by maxux** [comment]
`petep.3bot/peertube.flist` to what ?
Existing right now:
```
tf-official-apps/peertube-v3.1.1.flist 
tf-official-apps/threefoldtech-peertube-v3.0.flist
```

**Comment by ghost** [comment]
to one please https://hub.grid.tf/tf-official-apps/peertube-v3.1.1.flist
and i want another one with he latest tag also

**Comment by maxux** [comment]
![image](https://github.com/user-attachments/assets/3a7c80fc-6e22-4f43-8243-671746e30450)
