### ISSUE TITLE
Umbrel

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tf-images#273]

**Comment by PeterNashaat** [comment]
- Created new flist https://hub.grid.tf/petep.3bot/umbrel.flist that supports multiple ssh keys
- Created Pull Request with new changes here https://github.com/threefoldtech/tf-images/pull/274 
![image](https://github.com/threefoldtech/tf-images/assets/13523434/ebd7a596-721d-420f-b52b-2518e0f6c100)
![image](https://github.com/threefoldtech/tf-images/assets/13523434/0334aca6-3074-4a13-953f-532c2e08c6ef)
![image](https://github.com/threefoldtech/tf-images/assets/13523434/60292085-a8b5-44c9-8764-14baf50be688)

**Comment by PeterNashaat** [comment]
tested with 900G disk 

![Image](https://github.com/user-attachments/assets/a36aae9e-15a9-498b-9455-147886f3e686)

- Verified with bitcoin node

![Image](https://github.com/user-attachments/assets/aa5f64eb-ae08-4376-85d9-f1813ba2ebf5)

![Image](https://github.com/user-attachments/assets/00d46300-f42b-4066-8e47-76d3cc53dffb)

- Made sure that this user is needed https://github.com/threefoldtech/tf-images/blob/umbrel_v1.2.2/tfgrid3/umbrel/app/Dockerfile#L81

**Comment by xmonader** [comment]
Can be booted as a full vm
