### ISSUE TITLE
Always use different tags for k3s image updates

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tf-images#292]
With each update for the k3s image, please make sure to have a flist with a new tag to be used in the deployments cause we may run into errors when adding a new worker (has a new k3s version or new configuration) to an old cluster.

Please open an issue for ts-sdk and go-sdk with each new flist to be used.

**Comment by hossnys** [comment]
- as the latest k3s version released from k3s is [1.31.0](https://github.com/k3s-io/k3s/releases/tag/v1.31.0%2Bk3s1) , so we'll update our image to have this version but on base image 24.04 , and push a new image with the new released tag not using latest tag again.

**Comment by hossnys** [comment]
- changes made at this PR https://github.com/threefoldtech/tf-images/pull/299
- new docker image created : threefolddev/k3s:v1.31.0
- new flist also done here : https://hub.grid.tf/samir1.3bot/threefolddev-k3s-v1.31.0.flist

**Comment by hossnys** [comment]
- flist tested on devnet dashboard :

![Screenshot from 2024-09-23 15-59-29](https://github.com/user-attachments/assets/6169c8da-18bb-434c-a2f1-81d408eb2aed)

**Comment by hossnys** [comment]
- PR approved and merged .
- @maxux could you please promote this flist https://hub.grid.tf/samir1.3bot/threefolddev-k3s-v1.31.0.flist , using the same name please .

**Comment by maxux** [comment]
Promoted: https://hub.grid.tf/tf-official-apps/threefolddev-k3s-v1.31.0.flist.md

**Comment by hossnys** [comment]
done
