### ISSUE TITLE
Create Digibyte image for jukebox v1.0

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/tf-images#31]
## Background

Since Digibyte deployment via jukebox using different approach than using k8s cluster on vdc, we need a separate image of digibyte, with different requirements and acceptance criteria

## Requirements
requirements for each image not only for digibyte
1- docs showing the full/complete steps to deploy digibyte on a container
2- all required env vars with descriptions 
3- a working image 

## Acceptance Criteria

- [x] no kubectl exec command on front end or anything related specific to kubernetes

- [x] no manual interference during the deployments, deployment steps should be in a fully automated way we collect all required info in a chatflow and deploy after that without manual actions on the machine

**Comment by abdulgig** [comment]
This has already been implemented and working as expected. 

Related issues = https://github.com/threefoldtech/tf_jukebox/issues/40
Docs = [Digibyte Docs](https://github.com/threefoldtech/tf-images/blob/master/digibyte/README.md)
