### ISSUE TITLE
Create Dash image for jukebox

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf-images#33]
check description [here](https://github.com/threefoldtech/tf-images/issues/32)

**Comment by abdulgig** [comment]
The Dash image for JukeBox has been updated. Details under this link [Dash Image](https://github.com/threefoldtech/tf-images/tree/master/dash)

![image](https://user-images.githubusercontent.com/25789764/122754326-9323d280-d2a4-11eb-9e3f-22ae610babb0.png)

**Comment by ashraffouda** [comment]
Docker image not found, can u plz double check? or make it public or so?
![Screenshot from 2021-06-22 14-16-13](https://user-images.githubusercontent.com/1689456/122922975-78b12e00-d364-11eb-964f-6f1aae2e569a.png)

**Comment by abdulgig** [comment]
Dear @ashraffouda , it should be fine now. Please test
