### ISSUE TITLE
Create Casper image for jukebox

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf-images#35]
check description [here](https://github.com/threefoldtech/tf-images/issues/32)

**Comment by abdulgig** [comment]
The image and flist for casperlabs is ready. Please test and let us know

[Docs under this link](https://github.com/threefoldtech/tf-images/blob/master/casper/README.md)

![image](https://user-images.githubusercontent.com/25789764/123584995-70894080-d7f3-11eb-80a6-34219c9a8ee5.png)
![image](https://user-images.githubusercontent.com/25789764/123585215-da094f00-d7f3-11eb-85de-41346f0d0d9a.png)

**Comment by AhmedHanafy725** [comment]
Most of the time after deploying the container with Casper image, it stuck in the loading page.

![image](https://user-images.githubusercontent.com/41957921/123669716-aa326980-d83c-11eb-8f43-6894e808e593.png)

**Comment by abdulgig** [comment]
I'll investigate this , thanks for reporting that

**Comment by sasha-astiadi** [comment]
@xmonader casper part of 1.1 no? please remove from 1.0 project

**Comment by sasha-astiadi** [comment]
casper not for 1.1, change to tomochain, issue here https://github.com/threefoldtech/home/issues/1126 . removing this issue from project as later
