### ISSUE TITLE
substrate deployment - Error Connecting to Substrate 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tf-images#48]
integrating this flist https://github.com/threefoldtech/tf-images/tree/master/parity/substrate with Devnet jukebox deployer, I wasn't able to verify that the image works correctly.

![substrate2](https://user-images.githubusercontent.com/42457449/131250313-b3fcda9b-cce0-4065-8b89-1c82207628af.jpg)
![substrate3](https://user-images.githubusercontent.com/42457449/131250314-fc391148-bdb4-48bd-9645-7c83f97a92d8.jpg)
![substrate](https://user-images.githubusercontent.com/42457449/131250316-3276fda0-175d-4d63-a547-9f1eeaa0ee42.jpg)

**Comment by abdulgig** [comment]
@sameh-farouk  from the chatflow, we will need to pass on the assigned domain name to the environment variable "node_name" to our flist.

Can you please test again ?

![image](https://user-images.githubusercontent.com/25789764/132541768-f00c4bd8-f119-4299-9f19-cd78d78502d1.png)

**Comment by sameh-farouk** [comment]
we are not assigned a domain name to deployed nodes, we assign a public IPv6. so I assume you want to assign that ipv6 to the node_name env var on deployment?
