### ISSUE TITLE
misplaced Grid 3 images in grid2 directory

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tf-images#67]
centos-8 https://github.com/threefoldtech/tf-images/tree/development/tfgrid2/centos-8

ubuntu_20_debug https://github.com/threefoldtech/tf-images/tree/development/tfgrid2/ubuntu_20_debug

should be in grid3 directory in development branch

**Comment by xmonader** [comment]
please be more active on the issues in repos you own (this has been for 4 5 months) already with 0 updates
