### ISSUE TITLE
[k3s] kubelet runtime dir is not mounted on external disk

### ISSUE THREAD

**Issue by rcmorano** [threefoldtech/tf-images#83]
I found `/var/lib/kubelet` is not configured to use the external disk (by default at `/mydisk`), which by default only hosts what typically would be placed in `/var/lib/rancher` (pvcs, images...) but `emptyDir` kind of volumes are placed in the kubelet dir which currently takes up space from the rootfs and it's leading deployments to exhaust its disk quota. 

For example, an auxiliary volume like this [0] used as temporary disk space in an init container, is giving me problems.

[0]
```
      volumes:
      - name: aux-data-dir
        emptyDir: {}
```
[1]
```
Completed 978.2 MiB/2.7 GiB (2.6 MiB/s) download failed: s3://updates-cardano-testnet/cardano-db-sync/13/db-sync-snapshot-schema-13-block-3680594-x86_64.tgz to ./snapshot.tgz 
[Errno 122] Disk quota exceeded
```

**Comment by rcmorano** [comment]
I think it should be as easy to fix as adding an extra kubelet arg like this [0] here [1]

[0] `--kubelet-arg=root-dir=/mydisk/kubelet`
[1] https://github.com/threefoldtech/tf-images/blob/development/tfgrid3/k3s/scripts/entrypoint.sh#L14

**Comment by AhmedHanafy725** [comment]
@maxux can you please promote this flist? 
https://hub.grid.tf/hanafy.3bot/threefolddev-k3s-latest.flist -> https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist

**Comment by maxux** [comment]
https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist.md

**Comment by AhmedHanafy725** [comment]
@rcmorano a fix has been added to the image, thanks for reporting
