### ISSUE TITLE
review alll dockerfiles

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-images#9]
General guidelines

- All images shouldn't depend on existing images that we don't know how to build 
- Every dir should have the dockerfile, README.md on how to build and how to run
e.g in gitea_3bot it's based on threefolddev/gitea_3bot while we don't know how got build that image threefolddev/gitea_3bot

![image](https://user-images.githubusercontent.com/64129/89729401-adaadf80-da35-11ea-9e68-03c061e345ae.png)

broken images
- [ ] [couchdb](https://github.com/threefoldtech/tf-images/issues/10) data not there
- [x] [gitea](https://github.com/threefoldtech/tf-images/issues/13)
- [x] [forum](https://github.com/threefoldtech/tf-images/issues/12)
- [x] [discourse](https://github.com/threefoldtech/tf-images/issues/11)

**Comment by abom** [comment]
Some images include the trc binary, is there a download link or so? (e.g. [publishingtools](https://github.com/threefoldtech/tf-images/tree/master/publishingtools) and [nginx-certbot](https://github.com/threefoldtech/tf-images/tree/master/nginx-certbot))

If there's no pre-built binaries, we can at least track it once or so in the repo, e.g. a bin dir? and use this link/path in every image that needs it, at least we will have the same version...etc

**Comment by OmarElawady** [comment]
the startup script fails of the new discourse_3bot image fails with

`nginx: [emerg] unknown directive "brotli_static" in /etc/nginx/conf.d/discourse.conf:141`

Note: I ran it locally as a docker container so I removed the certbot certificate generation part before running the script.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tf-images/blob/master/gitea_all_in_one/Dockerfile#L1 gitea is still broken image @Pishoy

**Comment by Pishoy** [comment]
> https://github.com/threefoldtech/tf-images/blob/master/gitea_all_in_one/Dockerfile#L1 gitea is still broken image @Pishoy

as agreed, is not broken as it is referred to a pre-build image of https://github.com/threefoldtech/tf-gitea
